const std = @import("std");

pub const Miniz = struct {
    lib: *std.Build.Step.Compile,
    include_dir: std.Build.LazyPath,
};

pub fn add(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode) Miniz {
    const mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    // Static build — MINIZ_EXPORT is empty (normally generated by CMake/Meson)
    mod.addCMacro("MINIZ_EXPORT", "");

    const lib = b.addLibrary(.{
        .name = "miniz",
        .root_module = mod,
        .linkage = .static,
    });
    lib.linkLibC();
    lib.addIncludePath(b.path("deps/miniz"));
    lib.addCSourceFiles(.{
        .files = &.{
            "deps/miniz/miniz.c",
            "deps/miniz/miniz_tdef.c",
            "deps/miniz/miniz_tinfl.c",
            "deps/miniz/miniz_zip.c",
        },
    });

    return .{ .lib = lib, .include_dir = b.path("deps/miniz") };
}
