//! Inference-owned MLX macro-op FFI surface for Metal backend kernels.

const compute = @import("../../../../compute/root.zig");
const runtime_graph = @import("../runtime_graph.zig");

const mlx_graph = compute.metal.graph;

pub const ArrayHandle = mlx_graph.ArrayHandle;
pub const CacheHandle = runtime_graph.CacheHandle;
pub const ShortConvCacheHandle = runtime_graph.ShortConvCacheHandle;

pub extern fn mlx_lazy_shortconv_mixer_bf16(
    input: ArrayHandle,
    in_proj: ArrayHandle,
    conv_weight: ArrayHandle,
    conv_bias: ArrayHandle,
    out_proj: ArrayHandle,
    shortconv_cache: ShortConvCacheHandle,
    layer_idx: usize,
    d_conv: usize,
    conv_dim: usize,
) ArrayHandle;

pub extern fn mlx_lazy_shortconv_mixer_quantized(
    input: ArrayHandle,
    in_w: ArrayHandle,
    in_s: ArrayHandle,
    in_b: ArrayHandle,
    conv_weight: ArrayHandle,
    conv_bias: ArrayHandle,
    out_w: ArrayHandle,
    out_s: ArrayHandle,
    out_b: ArrayHandle,
    group_size: usize,
    bits: usize,
    shortconv_cache: ShortConvCacheHandle,
    layer_idx: usize,
    d_conv: usize,
    conv_dim: usize,
) ArrayHandle;

pub extern fn mlx_lazy_fused_attention(
    input: ArrayHandle,
    q_w: ArrayHandle,
    q_s: ArrayHandle,
    q_b: ArrayHandle,
    k_w: ArrayHandle,
    k_s: ArrayHandle,
    k_b: ArrayHandle,
    v_w: ArrayHandle,
    v_s: ArrayHandle,
    v_b: ArrayHandle,
    o_w: ArrayHandle,
    o_s: ArrayHandle,
    o_b: ArrayHandle,
    q_norm_w: ArrayHandle,
    k_norm_w: ArrayHandle,
    q_bias: ArrayHandle,
    k_bias: ArrayHandle,
    v_bias: ArrayHandle,
    o_bias: ArrayHandle,
    attn_sinks: ArrayHandle,
    cache_ptr: CacheHandle,
    layer_idx: usize,
    n_heads: usize,
    n_kv_heads: usize,
    head_dim: usize,
    pos_offset: usize,
    rope_theta: f32,
    runtime_rope_cos: ArrayHandle,
    runtime_rope_sin: ArrayHandle,
    runtime_rope_dim: usize,
    rms_eps: f32,
    group_size: usize,
    bits: usize,
    query_pre_attn_scalar: f32,
    attention_multiplier: f32,
) ArrayHandle;

pub extern fn mlx_lazy_fused_attention_qkv_quantized_o_dense(
    input: ArrayHandle,
    q_w: ArrayHandle,
    q_s: ArrayHandle,
    q_b: ArrayHandle,
    k_w: ArrayHandle,
    k_s: ArrayHandle,
    k_b: ArrayHandle,
    v_w: ArrayHandle,
    v_s: ArrayHandle,
    v_b: ArrayHandle,
    o_w: ArrayHandle,
    q_norm_w: ArrayHandle,
    k_norm_w: ArrayHandle,
    q_bias: ArrayHandle,
    k_bias: ArrayHandle,
    v_bias: ArrayHandle,
    o_bias: ArrayHandle,
    attn_sinks: ArrayHandle,
    cache_ptr: CacheHandle,
    layer_idx: usize,
    n_heads: usize,
    n_kv_heads: usize,
    head_dim: usize,
    pos_offset: usize,
    rope_theta: f32,
    runtime_rope_cos: ArrayHandle,
    runtime_rope_sin: ArrayHandle,
    runtime_rope_dim: usize,
    rms_eps: f32,
    group_size: usize,
    bits: usize,
    query_pre_attn_scalar: f32,
    attention_multiplier: f32,
) ArrayHandle;

pub extern fn mlx_lazy_fused_ffn(
    input: ArrayHandle,
    gate_w: ArrayHandle,
    gate_s: ArrayHandle,
    gate_b: ArrayHandle,
    up_w: ArrayHandle,
    up_s: ArrayHandle,
    up_b: ArrayHandle,
    down_w: ArrayHandle,
    down_s: ArrayHandle,
    down_b: ArrayHandle,
    group_size: usize,
    bits: usize,
    use_gelu: bool,
) ArrayHandle;

pub extern fn mlx_lazy_fused_attention_bf16(
    input: ArrayHandle,
    q_w: ArrayHandle,
    k_w: ArrayHandle,
    v_w: ArrayHandle,
    o_w: ArrayHandle,
    q_norm_w: ArrayHandle,
    k_norm_w: ArrayHandle,
    q_bias: ArrayHandle,
    k_bias: ArrayHandle,
    v_bias: ArrayHandle,
    o_bias: ArrayHandle,
    attn_sinks: ArrayHandle,
    cache_ptr: CacheHandle,
    layer_idx: usize,
    n_heads: usize,
    n_kv_heads: usize,
    head_dim: usize,
    pos_offset: usize,
    rope_theta: f32,
    runtime_rope_cos: ArrayHandle,
    runtime_rope_sin: ArrayHandle,
    runtime_rope_dim: usize,
    rms_eps: f32,
    query_pre_attn_scalar: f32,
    attention_multiplier: f32,
) ArrayHandle;

pub extern fn mlx_lazy_fused_ffn_bf16(
    input: ArrayHandle,
    gate_w: ArrayHandle,
    up_w: ArrayHandle,
    down_w: ArrayHandle,
) ArrayHandle;

pub extern fn mlx_lazy_fused_moe_ffn_mxfp4(
    input: ArrayHandle,
    router_w: ArrayHandle,
    router_s: ArrayHandle,
    router_b: ArrayHandle,
    router_bias: ArrayHandle,
    gate_w: ArrayHandle,
    gate_s: ArrayHandle,
    up_w: ArrayHandle,
    up_s: ArrayHandle,
    down_w: ArrayHandle,
    down_s: ArrayHandle,
    gate_bias: ArrayHandle,
    up_bias: ArrayHandle,
    down_bias: ArrayHandle,
    num_experts: usize,
    experts_per_token: usize,
    router_group_size: usize,
    expert_group_size: usize,
) ArrayHandle;
