// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//
// Generated by: zig build gen-bindings-rust
// Source:        core/src/capi/*.zig
// Generator:     core/helpers/gen_bindings_rust.zig
//
// Any manual edits WILL BE LOST on the next regeneration.
// To add safe wrappers, edit the generator template instead.
// =============================================================================

//! Low-level FFI bindings for libtalu.
//!
//! This crate provides raw, unsafe bindings to the C API of libtalu.
//! For a safe, idiomatic Rust API, use the `talu` crate instead.

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]

use std::os::raw::{c_char, c_int, c_void};

// =============================================================================
// Enums
// =============================================================================

/// Source: core/src/capi/router.zig
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum CPoolingStrategy {
    Last = 0,
    Mean = 1,
    First = 2,
}

impl From<u8> for CPoolingStrategy {
    fn from(value: u8) -> Self {
        match value {
            0 => CPoolingStrategy::Last,
            1 => CPoolingStrategy::Mean,
            2 => CPoolingStrategy::First,
            _ => CPoolingStrategy::First,
        }
    }
}

/// Source: core/src/converter/scheme.zig
#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Scheme {
    F16 = 4,
    Tq432 = 10,
    Tq464 = 11,
    Tq4128 = 12,
    Tq832 = 13,
    Tq864 = 14,
    Tq8128 = 15,
    Fp8E4m3 = 20,
    Fp8E5m2 = 21,
    Mxfp4 = 22,
    Nvfp4 = 23,
    Mxfp8 = 24,
}

impl From<u32> for Scheme {
    fn from(value: u32) -> Self {
        match value {
            4 => Scheme::F16,
            10 => Scheme::Tq432,
            11 => Scheme::Tq464,
            12 => Scheme::Tq4128,
            13 => Scheme::Tq832,
            14 => Scheme::Tq864,
            15 => Scheme::Tq8128,
            20 => Scheme::Fp8E4m3,
            21 => Scheme::Fp8E5m2,
            22 => Scheme::Mxfp4,
            23 => Scheme::Nvfp4,
            24 => Scheme::Mxfp8,
            _ => Scheme::Mxfp8,
        }
    }
}

/// Source: core/src/converter/scheme.zig
#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum QualityProfile {
    Best,
    Good,
    Custom,
}

impl From<u32> for QualityProfile {
    fn from(value: u32) -> Self {
        match value {
            _ => QualityProfile::Custom,
        }
    }
}

/// Source: core/src/router/batch.zig
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum EventType {
    TextDelta = 0,
    Completed = 1,
    Err = 2,
}

impl From<u8> for EventType {
    fn from(value: u8) -> Self {
        match value {
            0 => EventType::TextDelta,
            1 => EventType::Completed,
            2 => EventType::Err,
            _ => EventType::Err,
        }
    }
}

/// Source: core/src/router/capi_bridge.zig
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum CFinishReason {
    EosToken = 0,
    Length = 1,
    StopSequence = 2,
    ToolCalls = 3,
    ContentFilter = 4,
    Cancelled = 5,
}

impl From<u8> for CFinishReason {
    fn from(value: u8) -> Self {
        match value {
            0 => CFinishReason::EosToken,
            1 => CFinishReason::Length,
            2 => CFinishReason::StopSequence,
            3 => CFinishReason::ToolCalls,
            4 => CFinishReason::ContentFilter,
            5 => CFinishReason::Cancelled,
            _ => CFinishReason::Cancelled,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum LogFormat {
    Json = 0,
    Human = 1,
}

impl From<i32> for LogFormat {
    fn from(value: i32) -> Self {
        match value {
            0 => LogFormat::Json,
            1 => LogFormat::Human,
            _ => LogFormat::Human,
        }
    }
}

/// Source: core/src/capi/types.zig
#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum BackendType {
    Unspecified = -1,
    Local = 0,
}

impl From<i32> for BackendType {
    fn from(value: i32) -> Self {
        match value {
            -1 => BackendType::Unspecified,
            0 => BackendType::Local,
            _ => BackendType::Local,
        }
    }
}

/// Source: core/src/capi/error_codes.zig
#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ErrorCode {
    Ok = 0,
    ModelNotFound = 100,
    ModelInvalidFormat = 101,
    ModelUnsupportedArchitecture = 102,
    ModelConfigMissing = 103,
    ModelWeightsMissing = 104,
    ModelWeightsCorrupted = 105,
    TokenizerNotFound = 200,
    TokenizerInvalidFormat = 201,
    TokenizerEncodeFailed = 202,
    TokenizerDecodeFailed = 203,
    TokenizerInvalidTokenId = 204,
    GenerationFailed = 300,
    GenerationEmptyPrompt = 301,
    GenerationContextOverflow = 302,
    GenerationInvalidParams = 303,
    ConvertFailed = 400,
    ConvertUnsupportedFormat = 401,
    ConvertAlreadyQuantized = 402,
    ConvertOutputExists = 403,
    IoFileNotFound = 500,
    IoPermissionDenied = 501,
    IoReadFailed = 502,
    IoWriteFailed = 503,
    IoNetworkFailed = 504,
    IoPathInvalid = 505,
    IoPathOutsideWorkspace = 506,
    IoParentNotFound = 507,
    IoIsDirectory = 508,
    IoNotDirectory = 509,
    IoNotEmpty = 510,
    IoFileTooBig = 511,
    TemplateSyntaxError = 600,
    TemplateUndefinedVar = 601,
    TemplateTypeError = 602,
    TemplateRenderFailed = 603,
    TemplateNotFound = 604,
    TemplateInvalidJson = 605,
    TemplateRaiseException = 606,
    StorageError = 700,
    ResourceBusy = 701,
    ItemNotFound = 702,
    SessionNotFound = 703,
    TagNotFound = 704,
    ShellCommandDenied = 800,
    ShellExecFailed = 801,
    ShellSessionClosed = 802,
    ShellTimeout = 803,
    ShellProcessExited = 804,
    PolicyDeniedFileRead = 805,
    PolicyDeniedFileWrite = 806,
    PolicyDeniedFileDelete = 807,
    PolicyDeniedExec = 808,
    PolicyDeniedCwd = 809,
    PolicyInvalid = 810,
    PolicyStrictUnavailable = 811,
    PolicyStrictSetupFailed = 812,
    SandboxDetectFailed = 813,
    SandboxProbeFailed = 814,
    SandboxCgroupUnavailable = 815,
    OutOfMemory = 900,
    InvalidArgument = 901,
    InvalidHandle = 902,
    AmbiguousBackend = 903,
    UnsupportedAbiVersion = 904,
    ResourceExhausted = 905,
    InternalError = 999,
    TrainInvalidState = 1000,
    TrainModelLoadFailed = 1001,
    TrainAdapterConfigInvalid = 1002,
    TrainDataLoadFailed = 1003,
    TrainDataInvalidFormat = 1004,
    TrainNotConfigured = 1005,
    TrainAlreadyRunning = 1006,
    TrainCheckpointSaveFailed = 1007,
    TrainCheckpointLoadFailed = 1008,
    TrainStepFailed = 1009,
    TrainCancelled = 1010,
}

impl From<i32> for ErrorCode {
    fn from(value: i32) -> Self {
        match value {
            0 => ErrorCode::Ok,
            100 => ErrorCode::ModelNotFound,
            101 => ErrorCode::ModelInvalidFormat,
            102 => ErrorCode::ModelUnsupportedArchitecture,
            103 => ErrorCode::ModelConfigMissing,
            104 => ErrorCode::ModelWeightsMissing,
            105 => ErrorCode::ModelWeightsCorrupted,
            200 => ErrorCode::TokenizerNotFound,
            201 => ErrorCode::TokenizerInvalidFormat,
            202 => ErrorCode::TokenizerEncodeFailed,
            203 => ErrorCode::TokenizerDecodeFailed,
            204 => ErrorCode::TokenizerInvalidTokenId,
            300 => ErrorCode::GenerationFailed,
            301 => ErrorCode::GenerationEmptyPrompt,
            302 => ErrorCode::GenerationContextOverflow,
            303 => ErrorCode::GenerationInvalidParams,
            400 => ErrorCode::ConvertFailed,
            401 => ErrorCode::ConvertUnsupportedFormat,
            402 => ErrorCode::ConvertAlreadyQuantized,
            403 => ErrorCode::ConvertOutputExists,
            500 => ErrorCode::IoFileNotFound,
            501 => ErrorCode::IoPermissionDenied,
            502 => ErrorCode::IoReadFailed,
            503 => ErrorCode::IoWriteFailed,
            504 => ErrorCode::IoNetworkFailed,
            505 => ErrorCode::IoPathInvalid,
            506 => ErrorCode::IoPathOutsideWorkspace,
            507 => ErrorCode::IoParentNotFound,
            508 => ErrorCode::IoIsDirectory,
            509 => ErrorCode::IoNotDirectory,
            510 => ErrorCode::IoNotEmpty,
            511 => ErrorCode::IoFileTooBig,
            600 => ErrorCode::TemplateSyntaxError,
            601 => ErrorCode::TemplateUndefinedVar,
            602 => ErrorCode::TemplateTypeError,
            603 => ErrorCode::TemplateRenderFailed,
            604 => ErrorCode::TemplateNotFound,
            605 => ErrorCode::TemplateInvalidJson,
            606 => ErrorCode::TemplateRaiseException,
            700 => ErrorCode::StorageError,
            701 => ErrorCode::ResourceBusy,
            702 => ErrorCode::ItemNotFound,
            703 => ErrorCode::SessionNotFound,
            704 => ErrorCode::TagNotFound,
            800 => ErrorCode::ShellCommandDenied,
            801 => ErrorCode::ShellExecFailed,
            802 => ErrorCode::ShellSessionClosed,
            803 => ErrorCode::ShellTimeout,
            804 => ErrorCode::ShellProcessExited,
            805 => ErrorCode::PolicyDeniedFileRead,
            806 => ErrorCode::PolicyDeniedFileWrite,
            807 => ErrorCode::PolicyDeniedFileDelete,
            808 => ErrorCode::PolicyDeniedExec,
            809 => ErrorCode::PolicyDeniedCwd,
            810 => ErrorCode::PolicyInvalid,
            811 => ErrorCode::PolicyStrictUnavailable,
            812 => ErrorCode::PolicyStrictSetupFailed,
            813 => ErrorCode::SandboxDetectFailed,
            814 => ErrorCode::SandboxProbeFailed,
            815 => ErrorCode::SandboxCgroupUnavailable,
            900 => ErrorCode::OutOfMemory,
            901 => ErrorCode::InvalidArgument,
            902 => ErrorCode::InvalidHandle,
            903 => ErrorCode::AmbiguousBackend,
            904 => ErrorCode::UnsupportedAbiVersion,
            905 => ErrorCode::ResourceExhausted,
            999 => ErrorCode::InternalError,
            1000 => ErrorCode::TrainInvalidState,
            1001 => ErrorCode::TrainModelLoadFailed,
            1002 => ErrorCode::TrainAdapterConfigInvalid,
            1003 => ErrorCode::TrainDataLoadFailed,
            1004 => ErrorCode::TrainDataInvalidFormat,
            1005 => ErrorCode::TrainNotConfigured,
            1006 => ErrorCode::TrainAlreadyRunning,
            1007 => ErrorCode::TrainCheckpointSaveFailed,
            1008 => ErrorCode::TrainCheckpointLoadFailed,
            1009 => ErrorCode::TrainStepFailed,
            1010 => ErrorCode::TrainCancelled,
            _ => ErrorCode::TrainCancelled,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum LogLevel {
    Trace = 1,
    Debug = 5,
    Info = 9,
    Warn = 13,
    Err = 17,
    Fatal = 21,
    Off = 255,
}

impl From<i32> for LogLevel {
    fn from(value: i32) -> Self {
        match value {
            1 => LogLevel::Trace,
            5 => LogLevel::Debug,
            9 => LogLevel::Info,
            13 => LogLevel::Warn,
            17 => LogLevel::Err,
            21 => LogLevel::Fatal,
            255 => LogLevel::Off,
            _ => LogLevel::Off,
        }
    }
}

/// Source: core/src/converter/calibration_capture.zig
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ActivationRole {
    Generic,
    AttnInput,
    AttnOutput,
    FfnInput,
    FfnOutput,
}

impl From<u8> for ActivationRole {
    fn from(value: u8) -> Self {
        match value {
            _ => ActivationRole::FfnOutput,
        }
    }
}

/// Source: core/src/converter/scheme.zig
#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum QuantLevel {
    Q4 = 0,
    Q8 = 1,
    Q16 = 2,
}

impl From<u32> for QuantLevel {
    fn from(value: u32) -> Self {
        match value {
            0 => QuantLevel::Q4,
            1 => QuantLevel::Q8,
            2 => QuantLevel::Q16,
            _ => QuantLevel::Q16,
        }
    }
}

/// Source: core/src/capi/template.zig
#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum CSpanSourceType {
    StaticText = 0,
    Variable = 1,
    Expression = 2,
}

impl From<i32> for CSpanSourceType {
    fn from(value: i32) -> Self {
        match value {
            0 => CSpanSourceType::StaticText,
            1 => CSpanSourceType::Variable,
            2 => CSpanSourceType::Expression,
            _ => CSpanSourceType::Expression,
        }
    }
}

/// Source: core/src/capi/converter.zig
#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum QuantMethodEnum {
    None = 0,
    Gaffine = 1,
    Mxfp4 = 2,
    Native = 3,
    Fp8 = 4,
    Mxfp8 = 5,
}

impl From<i32> for QuantMethodEnum {
    fn from(value: i32) -> Self {
        match value {
            0 => QuantMethodEnum::None,
            1 => QuantMethodEnum::Gaffine,
            2 => QuantMethodEnum::Mxfp4,
            3 => QuantMethodEnum::Native,
            4 => QuantMethodEnum::Fp8,
            5 => QuantMethodEnum::Mxfp8,
            _ => QuantMethodEnum::Mxfp8,
        }
    }
}

/// Source: core/src/converter/scheme.zig
#[repr(u32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Platform {
    Cpu = 0,
    Metal = 1,
    Cuda = 2,
}

impl From<u32> for Platform {
    fn from(value: u32) -> Self {
        match value {
            0 => Platform::Cpu,
            1 => Platform::Metal,
            2 => Platform::Cuda,
            _ => Platform::Cuda,
        }
    }
}

// =============================================================================
// Structures
// =============================================================================

/// Source: core/src/converter/scheme.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ConvertOptions {
    pub scheme: Scheme,
    pub force: bool,
    pub offline: bool,
    pub destination: *const c_char,
    pub overrides: [OverrideRule; 32],
    pub num_overrides: u32,
    pub max_shard_size: u64,
    pub dry_run: bool,
    pub return_model_id: bool,
    pub platform: Platform,
    pub quant: QuantLevel,
    pub use_platform_quant: bool,
    pub calibration_profile: QualityProfile,
    pub calibration_seed: u64,
    pub calibration_iters: u32,
    pub calibration_nsamples: u32,
    pub calibration_seqlen: u32,
    pub calibration_batch_size: u32,
    pub calibration_nblocks: u32,
    pub progress_callback: *mut c_void,
    pub progress_user_data: *mut c_void,
}

impl Default for ConvertOptions {
    fn default() -> Self {
        Self {
            scheme: Scheme::from(0),
            force: false,
            offline: false,
            destination: std::ptr::null(),
            overrides: [OverrideRule::default(); 32],
            num_overrides: 0,
            max_shard_size: 0,
            dry_run: false,
            return_model_id: false,
            platform: Platform::from(0),
            quant: QuantLevel::from(0),
            use_platform_quant: false,
            calibration_profile: QualityProfile::from(0),
            calibration_seed: 42,
            calibration_iters: 0,
            calibration_nsamples: 0,
            calibration_seqlen: 0,
            calibration_batch_size: 0,
            calibration_nblocks: 0,
            progress_callback: std::ptr::null_mut(),
            progress_user_data: std::ptr::null_mut(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CFullSessionInfo {
    pub current_step: u64,
    pub total_steps: u64,
    pub total_params: u64,
    pub batch_size: u32,
    pub state: u8,
    pub _padding: [u8; 3],
}

impl Default for CFullSessionInfo {
    fn default() -> Self {
        Self {
            current_step: 0,
            total_steps: 0,
            total_params: 0,
            batch_size: 0,
            state: 0,
            _padding: [0; 3],
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CTransformerConfig {
    pub vocab_size: u32,
    pub d_model: u32,
    pub num_layers: u32,
    pub num_heads: u32,
    pub num_kv_heads: u32,
    pub d_ff: u32,
    pub seq_len: u32,
    pub rope_theta: f32,
    pub norm_eps: f32,
}

impl Default for CTransformerConfig {
    fn default() -> Self {
        Self {
            vocab_size: 0,
            d_model: 0,
            num_layers: 0,
            num_heads: 0,
            num_kv_heads: 0,
            d_ff: 0,
            seq_len: 0,
            rope_theta: 0.0,
            norm_eps: 0.0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TokenizeResult {
    pub tokens: *const *const c_char,
    pub num_tokens: usize,
    pub error_msg: *const u8,
}

impl Default for TokenizeResult {
    fn default() -> Self {
        Self {
            tokens: std::ptr::null(),
            num_tokens: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/router.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CModelInfo {
    pub file_size: u64,
    pub tensor_count: u64,
    pub vocab_size: c_int,
    pub d_model: c_int,
    pub n_layers: c_int,
    pub n_heads: c_int,
    pub n_kv_groups: c_int,
    pub d_ff: c_int,
    pub max_seq_len: c_int,
    pub gaffine_group_size: c_int,
    pub weight_dtype: u8,
    pub _pad: [u8; 7],
}

impl Default for CModelInfo {
    fn default() -> Self {
        Self {
            file_size: 0,
            tensor_count: 0,
            vocab_size: 0,
            d_model: 0,
            n_layers: 0,
            n_heads: 0,
            n_kv_groups: 0,
            d_ff: 0,
            max_seq_len: 0,
            gaffine_group_size: 0,
            weight_dtype: 0,
            _pad: [0; 7],
        }
    }
}

/// Source: core/src/capi/validate.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ValidateConfigC {
    pub allow_thinking: bool,
    pub max_thinking_tokens: usize,
    pub start_marker: *const c_char,
    pub soft_limit_ratio: f32,
    pub soft_limit_bias: f32,
}

impl Default for ValidateConfigC {
    fn default() -> Self {
        Self {
            allow_thinking: false,
            max_thinking_tokens: 512,
            start_marker: std::ptr::null(),
            soft_limit_ratio: 0.9,
            soft_limit_bias: -2.0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TokenizeBytesResult {
    pub data: *mut u8,
    pub data_len: usize,
    pub offsets: *mut usize,
    pub num_tokens: usize,
    pub error_msg: *const u8,
}

impl Default for TokenizeBytesResult {
    fn default() -> Self {
        Self {
            data: std::ptr::null_mut(),
            data_len: 0,
            offsets: std::ptr::null_mut(),
            num_tokens: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CReasoningItem {
    pub content_count: usize,
    pub summary_count: usize,
    pub encrypted_content_ptr: *const u8,
    pub encrypted_content_len: usize,
}

impl Default for CReasoningItem {
    fn default() -> Self {
        Self {
            content_count: 0,
            summary_count: 0,
            encrypted_content_ptr: std::ptr::null(),
            encrypted_content_len: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct EncodeResult {
    pub ids: *mut u32,
    pub offsets: *mut TokenOffset,
    pub attention_mask: *mut u32,
    pub special_tokens_mask: *mut u32,
    pub num_tokens: usize,
    pub error_msg: *const u8,
}

impl Default for EncodeResult {
    fn default() -> Self {
        Self {
            ids: std::ptr::null_mut(),
            offsets: std::ptr::null_mut(),
            attention_mask: std::ptr::null_mut(),
            special_tokens_mask: std::ptr::null_mut(),
            num_tokens: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GenerationConfigInfo {
    pub temperature: f32,
    pub top_k: usize,
    pub top_p: f32,
    pub do_sample: bool,
}

impl Default for GenerationConfigInfo {
    fn default() -> Self {
        Self {
            temperature: 0.0,
            top_k: 0,
            top_p: 0.0,
            do_sample: false,
        }
    }
}

/// Source: core/src/router/capi_bridge.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CLogitBiasEntry {
    pub token_id: u32,
    pub bias: f32,
}

impl Default for CLogitBiasEntry {
    fn default() -> Self {
        Self {
            token_id: 0,
            bias: 0.0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TensorStats {
    pub count: u64,
    pub min: f32,
    pub max: f32,
    pub mean: f32,
    pub rms: f32,
    pub nan_count: u32,
    pub inf_count: u32,
}

impl Default for TensorStats {
    fn default() -> Self {
        Self {
            count: 0,
            min: 0.0,
            max: 0.0,
            mean: 0.0,
            rms: 0.0,
            nan_count: 0,
            inf_count: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct EosTokenResult {
    pub tokens: *mut u32,
    pub num_tokens: usize,
}

impl Default for EosTokenResult {
    fn default() -> Self {
        Self {
            tokens: std::ptr::null_mut(),
            num_tokens: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct EncodeOptions {
    pub add_bos: u8,
    pub add_eos: u8,
    pub truncation: u8,
    pub truncation_side: u8,
    pub _padding: [u8; 4],
    pub max_length: usize,
}

impl Default for EncodeOptions {
    fn default() -> Self {
        Self {
            add_bos: 0,
            add_eos: 0,
            truncation: 0,
            truncation_side: 0,
            _padding: [0; 4],
            max_length: 0,
        }
    }
}

/// Source: core/src/capi/converter.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ModelInfo {
    pub vocab_size: c_int,
    pub hidden_size: c_int,
    pub num_layers: c_int,
    pub num_heads: c_int,
    pub num_kv_heads: c_int,
    pub intermediate_size: c_int,
    pub max_seq_len: c_int,
    pub head_dim: c_int,
    pub rope_theta: f32,
    pub norm_eps: f32,
    pub quant_bits: c_int,
    pub quant_group_size: c_int,
    pub quant_method: QuantMethodEnum,
    pub model_type: *const c_char,
    pub architecture: *const c_char,
    pub tie_word_embeddings: bool,
    pub use_gelu: bool,
    pub num_experts: c_int,
    pub experts_per_token: c_int,
    pub error_msg: *const c_char,
}

impl Default for ModelInfo {
    fn default() -> Self {
        Self {
            vocab_size: 0,
            hidden_size: 0,
            num_layers: 0,
            num_heads: 0,
            num_kv_heads: 0,
            intermediate_size: 0,
            max_seq_len: 0,
            head_dim: 0,
            rope_theta: 0.0,
            norm_eps: 0.0,
            quant_bits: 0,
            quant_group_size: 0,
            quant_method: QuantMethodEnum::from(0),
            model_type: std::ptr::null(),
            architecture: std::ptr::null(),
            tie_word_embeddings: false,
            use_gelu: false,
            num_experts: 0,
            experts_per_token: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CBatchConfig {
    pub max_concurrent: usize,
}

impl Default for CBatchConfig {
    fn default() -> Self {
        Self { max_concurrent: 0 }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CFunctionCallItem {
    pub name_ptr: *const c_char,
    pub call_id_ptr: *const c_char,
    pub arguments_ptr: *const u8,
    pub arguments_len: usize,
}

impl Default for CFunctionCallItem {
    fn default() -> Self {
        Self {
            name_ptr: std::ptr::null(),
            call_id_ptr: std::ptr::null(),
            arguments_ptr: std::ptr::null(),
            arguments_len: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct DecodeOptionsC {
    pub skip_special_tokens: c_int,
}

impl Default for DecodeOptionsC {
    fn default() -> Self {
        Self {
            skip_special_tokens: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CContentPart {
    pub content_type: u8,
    pub image_detail: u8,
    pub _padding: [u8; 6],
    pub data_ptr: *const u8,
    pub data_len: usize,
    pub secondary_ptr: *const u8,
    pub secondary_len: usize,
    pub tertiary_ptr: *const u8,
    pub tertiary_len: usize,
    pub quaternary_ptr: *const u8,
    pub quaternary_len: usize,
}

impl Default for CContentPart {
    fn default() -> Self {
        Self {
            content_type: 0,
            image_detail: 0,
            _padding: [0; 6],
            data_ptr: std::ptr::null(),
            data_len: 0,
            secondary_ptr: std::ptr::null(),
            secondary_len: 0,
            tertiary_ptr: std::ptr::null(),
            tertiary_len: 0,
            quaternary_ptr: std::ptr::null(),
            quaternary_len: 0,
        }
    }
}

/// Source: core/src/router/capi_bridge.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CGenerateVisionImage {
    pub pixels_ptr: *const f32,
    pub pixel_count: usize,
    pub width: u32,
    pub height: u32,
    pub grid_temporal: u32,
    pub grid_height: u32,
    pub grid_width: u32,
    pub token_count: usize,
}

impl Default for CGenerateVisionImage {
    fn default() -> Self {
        Self {
            pixels_ptr: std::ptr::null(),
            pixel_count: 0,
            width: 0,
            height: 0,
            grid_temporal: 0,
            grid_height: 0,
            grid_width: 0,
            token_count: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CFunctionCallOutputItem {
    pub call_id_ptr: *const c_char,
    pub output_text_ptr: *const u8,
    pub output_text_len: usize,
    pub output_parts_count: usize,
    pub is_text_output: bool,
    pub _padding: [u8; 7],
}

impl Default for CFunctionCallOutputItem {
    fn default() -> Self {
        Self {
            call_id_ptr: std::ptr::null(),
            output_text_ptr: std::ptr::null(),
            output_text_len: 0,
            output_parts_count: 0,
            is_text_output: false,
            _padding: [0; 7],
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CMessageItem {
    pub role: u8,
    pub _padding: [u8; 7],
    pub content_count: usize,
    pub raw_role_ptr: *const c_char,
}

impl Default for CMessageItem {
    fn default() -> Self {
        Self {
            role: 0,
            _padding: [0; 7],
            content_count: 0,
            raw_role_ptr: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CapturedTensorInfo {
    pub point: u8,
    pub layer: u16,
    pub token: u32,
    pub position: u32,
    pub backend: u8,
    pub shape: [u32; 4],
    pub ndim: u8,
    pub dtype: u8,
    pub kernel_name: [u8; 48],
    pub work_flops: u64,
    pub work_bytes: u64,
    pub stats: TensorStats,
    pub timestamp_ns: i64,
}

impl Default for CapturedTensorInfo {
    fn default() -> Self {
        Self {
            point: 0,
            layer: 0,
            token: 0,
            position: 0,
            backend: 0,
            shape: [0; 4],
            ndim: 0,
            dtype: 0,
            kernel_name: [0; 48],
            work_flops: 0,
            work_bytes: 0,
            stats: TensorStats::default(),
            timestamp_ns: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct QueryResult {
    pub results: *mut CapturedTensorInfo,
    pub count: usize,
    pub error_msg: *const c_char,
}

impl Default for QueryResult {
    fn default() -> Self {
        Self {
            results: std::ptr::null_mut(),
            count: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CItemReferenceItem {
    pub id_ptr: *const c_char,
}

impl Default for CItemReferenceItem {
    fn default() -> Self {
        Self {
            id_ptr: std::ptr::null(),
        }
    }
}

/// Source: core/src/converter/scheme.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct OverrideRule {
    pub pattern: *const c_char,
    pub scheme: Scheme,
}

impl Default for OverrideRule {
    fn default() -> Self {
        Self {
            pattern: std::ptr::null(),
            scheme: Scheme::from(0),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TokenOffset {
    pub start: u32,
    pub end: u32,
}

impl Default for TokenOffset {
    fn default() -> Self {
        Self { start: 0, end: 0 }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SpecialTokensResult {
    pub bos_token_id: c_int,
    pub unk_token_id: c_int,
    pub pad_token_id: c_int,
}

impl Default for SpecialTokensResult {
    fn default() -> Self {
        Self {
            bos_token_id: 0,
            unk_token_id: 0,
            pad_token_id: 0,
        }
    }
}

/// Source: core/src/capi/types.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TaluCapabilities {
    pub abi_version: u32,
    pub struct_size: u32,
    pub streaming: u8,
    pub tool_calling: u8,
    pub logprobs: u8,
    pub embeddings: u8,
    pub json_schema: u8,
    pub _reserved: [u8; 32],
}

impl Default for TaluCapabilities {
    fn default() -> Self {
        Self {
            abi_version: 0,
            struct_size: 0,
            streaming: 0,
            tool_calling: 0,
            logprobs: 0,
            embeddings: 0,
            json_schema: 0,
            _reserved: [0; 32],
        }
    }
}

/// Source: core/src/capi/converter.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ConvertResult {
    pub output_path: *const c_char,
    pub error_msg: *const c_char,
    pub success: bool,
}

impl Default for ConvertResult {
    fn default() -> Self {
        Self {
            output_path: std::ptr::null(),
            error_msg: std::ptr::null(),
            success: false,
        }
    }
}

/// Source: core/src/capi/types.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct LocalConfig {
    pub gpu_layers: c_int,
    pub use_mmap: u8,
    pub num_threads: c_int,
    pub _reserved: [u8; 32],
}

impl Default for LocalConfig {
    fn default() -> Self {
        Self {
            gpu_layers: 0,
            use_mmap: 0,
            num_threads: 0,
            _reserved: [0; 32],
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ChatCreateOptions {
    pub offline: bool,
}

impl Default for ChatCreateOptions {
    fn default() -> Self {
        Self { offline: false }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CBatchEvent {
    pub request_id: u64,
    pub event_type: u8,
    pub item_type: u8,
    pub content_type: u8,
    pub is_final: u8,
    pub _pad: [u8; 4],
    pub text_ptr: *const u8,
    pub text_len: usize,
    pub token_id: u32,
    pub _pad2: [u8; 4],
    pub tokens_generated: usize,
    pub timestamp_ns: i64,
}

impl Default for CBatchEvent {
    fn default() -> Self {
        Self {
            request_id: 0,
            event_type: 0,
            item_type: 0,
            content_type: 0,
            is_final: 0,
            _pad: [0; 4],
            text_ptr: std::ptr::null(),
            text_len: 0,
            token_id: 0,
            _pad2: [0; 4],
            tokens_generated: 0,
            timestamp_ns: 0,
        }
    }
}

/// Source: core/src/capi/converter.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ExecutionPlanInfo {
    pub matmul_kernel: *const c_char,
    pub attention_type: *const c_char,
    pub ffn_type: *const c_char,
    pub num_layers: c_int,
    pub hidden_size: c_int,
    pub num_heads: c_int,
    pub num_kv_heads: c_int,
    pub head_dim: c_int,
    pub num_experts: c_int,
    pub experts_per_token: c_int,
    pub quant_bits: c_int,
    pub quant_group_size: c_int,
    pub uses_gqa: bool,
    pub uses_moe: bool,
    pub uses_quantization: bool,
    pub uses_gelu: bool,
    pub is_supported: bool,
    pub error_msg: *const c_char,
}

impl Default for ExecutionPlanInfo {
    fn default() -> Self {
        Self {
            matmul_kernel: std::ptr::null(),
            attention_type: std::ptr::null(),
            ffn_type: std::ptr::null(),
            num_layers: 0,
            hidden_size: 0,
            num_heads: 0,
            num_kv_heads: 0,
            head_dim: 0,
            num_experts: 0,
            experts_per_token: 0,
            quant_bits: 0,
            quant_group_size: 0,
            uses_gqa: false,
            uses_moe: false,
            uses_quantization: false,
            uses_gelu: false,
            is_supported: false,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct BatchEncodeResult {
    pub ids: *mut u32,
    pub offsets: *mut usize,
    pub total_tokens: usize,
    pub num_sequences: usize,
    pub error_msg: *const u8,
}

impl Default for BatchEncodeResult {
    fn default() -> Self {
        Self {
            ids: std::ptr::null_mut(),
            offsets: std::ptr::null_mut(),
            total_tokens: 0,
            num_sequences: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/router/capi_bridge.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CGenerateConfig {
    pub max_tokens: usize,
    pub max_completion_tokens: usize,
    pub max_reasoning_tokens: usize,
    pub temperature: f32,
    pub top_k: usize,
    pub top_p: f32,
    pub min_p: f32,
    pub repetition_penalty: f32,
    pub presence_penalty: f32,
    pub frequency_penalty: f32,
    pub stop_sequences: *const *const c_char,
    pub stop_sequence_count: usize,
    pub logit_bias: *const CLogitBiasEntry,
    pub logit_bias_count: usize,
    pub seed: u64,
    pub template_override: *const c_char,
    pub extra_context_json: *const c_char,
    pub reasoning_effort: *const c_char,
    pub tools_json: *const c_char,
    pub tool_choice: *const c_char,
    pub stop_flag: *mut c_void,
    pub extra_body_json: *const c_char,
    pub raw_output: usize,
    pub completions_mode: usize,
    pub prefill_progress_fn: *mut c_void,
    pub prefill_progress_data: *mut c_void,
    pub external_vision_images: *const CGenerateVisionImage,
    pub external_vision_image_count: usize,
    pub external_vision_image_token_id: u32,
    pub _external_vision_padding: u32,
}

impl Default for CGenerateConfig {
    fn default() -> Self {
        Self {
            max_tokens: 0,
            max_completion_tokens: 0,
            max_reasoning_tokens: usize::MAX,
            temperature: -1.0,
            top_k: 0,
            top_p: -1.0,
            min_p: -1.0,
            repetition_penalty: -1.0,
            presence_penalty: -1.0,
            frequency_penalty: -1.0,
            stop_sequences: std::ptr::null(),
            stop_sequence_count: 0,
            logit_bias: std::ptr::null(),
            logit_bias_count: 0,
            seed: 0,
            template_override: std::ptr::null(),
            extra_context_json: std::ptr::null(),
            reasoning_effort: std::ptr::null(),
            tools_json: std::ptr::null(),
            tool_choice: std::ptr::null(),
            stop_flag: std::ptr::null_mut(),
            extra_body_json: std::ptr::null(),
            raw_output: 0,
            completions_mode: 0,
            prefill_progress_fn: std::ptr::null_mut(),
            prefill_progress_data: std::ptr::null_mut(),
            external_vision_images: std::ptr::null(),
            external_vision_image_count: 0,
            external_vision_image_token_id: 0,
            _external_vision_padding: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SamplingParams {
    pub strategy: u32,
    pub temperature: f32,
    pub top_k: u32,
    pub top_p: f32,
    pub min_p: f32,
    pub repetition_penalty: f32,
    pub seed: u64,
}

impl Default for SamplingParams {
    fn default() -> Self {
        Self {
            strategy: 0,
            temperature: 1.0,
            top_k: 50,
            top_p: 0.9,
            min_p: 0.0,
            repetition_penalty: 1.0,
            seed: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CBatchResult {
    pub prompt_tokens: usize,
    pub completion_tokens: usize,
    pub prefill_ns: u64,
    pub generation_ns: u64,
    pub ttft_ns: u64,
    pub finish_reason: u8,
    pub _pad: [u8; 7],
    pub text: *const c_char,
    pub tool_calls: *const CToolCallRef,
    pub tool_call_count: usize,
    pub error_code: c_int,
    pub _pad2: [u8; 4],
}

impl Default for CBatchResult {
    fn default() -> Self {
        Self {
            prompt_tokens: 0,
            completion_tokens: 0,
            prefill_ns: 0,
            generation_ns: 0,
            ttft_ns: 0,
            finish_reason: 0,
            _pad: [0; 7],
            text: std::ptr::null(),
            tool_calls: std::ptr::null(),
            tool_call_count: 0,
            error_code: 0,
            _pad2: [0; 4],
        }
    }
}

/// Source: core/src/capi/types.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub union BackendUnion {
    pub local: LocalConfig,
}

/// Source: core/src/capi/validate.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SemanticViolationC {
    pub path: *const c_char,
    pub message: *const c_char,
    pub constraint_type: c_int,
}

impl Default for SemanticViolationC {
    fn default() -> Self {
        Self {
            path: std::ptr::null(),
            message: std::ptr::null(),
            constraint_type: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct EffectiveGenConfig {
    pub temperature: f32,
    pub top_k: usize,
    pub top_p: f32,
    pub min_p: f32,
    pub repetition_penalty: f32,
    pub presence_penalty: f32,
    pub frequency_penalty: f32,
    pub seed: u64,
    pub max_tokens: usize,
    pub do_sample: bool,
}

impl Default for EffectiveGenConfig {
    fn default() -> Self {
        Self {
            temperature: 0.0,
            top_k: 0,
            top_p: 0.0,
            min_p: 0.0,
            repetition_penalty: 0.0,
            presence_penalty: 0.0,
            frequency_penalty: 0.0,
            seed: 0,
            max_tokens: 0,
            do_sample: false,
        }
    }
}

/// Source: core/src/capi/router.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct BackendCreateOptions {
    pub progress_callback: *mut c_void,
    pub progress_user_data: *mut c_void,
}

impl Default for BackendCreateOptions {
    fn default() -> Self {
        Self {
            progress_callback: std::ptr::null_mut(),
            progress_user_data: std::ptr::null_mut(),
        }
    }
}

/// Source: core/src/capi/types.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TaluModelSpec {
    pub abi_version: u32,
    pub struct_size: u32,
    pub ref_: *const c_char,
    pub backend_type_raw: c_int,
    pub backend_config: BackendUnion,
}

impl Default for TaluModelSpec {
    fn default() -> Self {
        Self {
            abi_version: 0,
            struct_size: 0,
            ref_: std::ptr::null(),
            backend_type_raw: 0,
            backend_config: unsafe { std::mem::zeroed() },
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct PaddedTensorOptions {
    pub pad_id: u32,
    pub padding_side: u8,
    pub max_length: usize,
    pub truncate: bool,
    pub return_attention_mask: bool,
}

impl Default for PaddedTensorOptions {
    fn default() -> Self {
        Self {
            pad_id: 0,
            padding_side: 0,
            max_length: 0,
            truncate: false,
            return_attention_mask: false,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct DownloadOptions {
    pub token: *const c_char,
    pub progress_callback: *mut c_void,
    pub user_data: *mut c_void,
    pub force: bool,
    pub endpoint_url: *const c_char,
    pub skip_weights: bool,
    pub cancel_flag: *mut c_void,
}

impl Default for DownloadOptions {
    fn default() -> Self {
        Self {
            token: std::ptr::null(),
            progress_callback: std::ptr::null_mut(),
            user_data: std::ptr::null_mut(),
            force: false,
            endpoint_url: std::ptr::null(),
            skip_weights: false,
            cancel_flag: std::ptr::null_mut(),
        }
    }
}

/// Source: core/src/router/capi_bridge.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CToolCallRef {
    pub item_index: usize,
    pub call_id: *const c_char,
    pub name: *const c_char,
    pub arguments: *const c_char,
}

impl Default for CToolCallRef {
    fn default() -> Self {
        Self {
            item_index: 0,
            call_id: std::ptr::null(),
            name: std::ptr::null(),
            arguments: std::ptr::null(),
        }
    }
}

/// Source: core/src/router/capi_bridge.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GenerateContentPart {
    pub content_type: u8,
    pub data_ptr: *const u8,
    pub data_len: usize,
    pub mime_ptr: *const c_char,
}

impl Default for GenerateContentPart {
    fn default() -> Self {
        Self {
            content_type: 0,
            data_ptr: std::ptr::null(),
            data_len: 0,
            mime_ptr: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/validate.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct SemanticValidationResultC {
    pub is_valid: bool,
    pub path: *const c_char,
    pub message: *const c_char,
}

impl Default for SemanticValidationResultC {
    fn default() -> Self {
        Self {
            is_valid: false,
            path: std::ptr::null(),
            message: std::ptr::null(),
        }
    }
}

/// Source: core/src/router/batch.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CEvent {
    pub request_id: u64,
    pub event_type: u8,
    pub item_type: u8,
    pub content_type: u8,
    pub is_final: u8,
    pub _pad: [u8; 4],
    pub text_ptr: *const u8,
    pub text_len: usize,
    pub token_id: u32,
    pub _pad2: [u8; 4],
    pub tokens_generated: usize,
    pub timestamp_ns: i64,
}

impl Default for CEvent {
    fn default() -> Self {
        Self {
            request_id: 0,
            event_type: 0,
            item_type: 0,
            content_type: 0,
            is_final: 0,
            _pad: [0; 4],
            text_ptr: std::ptr::null(),
            text_len: 0,
            token_id: 0,
            _pad2: [0; 4],
            tokens_generated: 0,
            timestamp_ns: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct DecodeResult {
    pub text: *mut u8,
    pub text_len: usize,
    pub error_msg: *const u8,
}

impl Default for DecodeResult {
    fn default() -> Self {
        Self {
            text: std::ptr::null_mut(),
            text_len: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct PaddedTensorResult {
    pub input_ids: *mut u32,
    pub attention_mask: *mut u32,
    pub num_sequences: usize,
    pub padded_length: usize,
    pub error_msg: *const u8,
}

impl Default for PaddedTensorResult {
    fn default() -> Self {
        Self {
            input_ids: std::ptr::null_mut(),
            attention_mask: std::ptr::null_mut(),
            num_sequences: 0,
            padded_length: 0,
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VocabResult {
    pub tokens: *const *const c_char,
    pub lengths: *mut u32,
    pub num_entries: usize,
    pub ids: *mut u32,
    pub error_msg: *const u8,
}

impl Default for VocabResult {
    fn default() -> Self {
        Self {
            tokens: std::ptr::null(),
            lengths: std::ptr::null_mut(),
            num_entries: 0,
            ids: std::ptr::null_mut(),
            error_msg: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/template.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct COutputSpan {
    pub start: u32,
    pub end: u32,
    pub source_type: CSpanSourceType,
    pub variable_path: *const c_char,
}

impl Default for COutputSpan {
    fn default() -> Self {
        Self {
            start: 0,
            end: 0,
            source_type: CSpanSourceType::from(0),
            variable_path: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CItem {
    pub id: u64,
    pub item_type: u8,
    pub status: u8,
    pub _padding: [u8; 6],
    pub created_at_ms: i64,
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub prefill_ns: u64,
    pub generation_ns: u64,
    pub finish_reason_ptr: *const c_char,
}

impl Default for CItem {
    fn default() -> Self {
        Self {
            id: 0,
            item_type: 0,
            status: 0,
            _padding: [0; 6],
            created_at_ms: 0,
            input_tokens: 0,
            output_tokens: 0,
            prefill_ns: 0,
            generation_ns: 0,
            finish_reason_ptr: std::ptr::null(),
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CFullSessionConfig {
    pub learning_rate: f32,
    pub min_learning_rate: f32,
    pub weight_decay: f32,
    pub beta1: f32,
    pub beta2: f32,
    pub epsilon: f32,
    pub max_grad_norm: f32,
    pub batch_size: u32,
    pub warmup_steps: u64,
    pub total_steps: u64,
}

impl Default for CFullSessionConfig {
    fn default() -> Self {
        Self {
            learning_rate: 0.0,
            min_learning_rate: 0.0,
            weight_decay: 0.0,
            beta1: 0.0,
            beta2: 0.0,
            epsilon: 0.0,
            max_grad_norm: 0.0,
            batch_size: 0,
            warmup_steps: 0,
            total_steps: 0,
        }
    }
}

/// Source: core/src/router/capi_bridge.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CGenerateResult {
    pub text: *const c_char,
    pub token_count: usize,
    pub prompt_tokens: usize,
    pub completion_tokens: usize,
    pub prefill_ns: u64,
    pub generation_ns: u64,
    pub ttft_ns: u64,
    pub error_code: c_int,
    pub finish_reason: u8,
    pub _padding: [u8; 3],
    pub tool_calls: *const CToolCallRef,
    pub tool_call_count: usize,
}

impl Default for CGenerateResult {
    fn default() -> Self {
        Self {
            text: std::ptr::null(),
            token_count: 0,
            prompt_tokens: 0,
            completion_tokens: 0,
            prefill_ns: 0,
            generation_ns: 0,
            ttft_ns: 0,
            error_code: 0,
            finish_reason: 0,
            _padding: [0; 3],
            tool_calls: std::ptr::null(),
            tool_call_count: 0,
        }
    }
}

/// Source: core/src/capi/root.zig
#[repr(C)]
#[derive(Copy, Clone)]
pub struct EffectiveGenConfigRequest {
    pub temperature: f32,
    pub top_k: usize,
    pub top_p: f32,
    pub min_p: f32,
    pub repetition_penalty: f32,
    pub presence_penalty: f32,
    pub frequency_penalty: f32,
    pub seed: u64,
    pub max_tokens: usize,
}

impl Default for EffectiveGenConfigRequest {
    fn default() -> Self {
        Self {
            temperature: -1.0,
            top_k: 0,
            top_p: -1.0,
            min_p: -1.0,
            repetition_penalty: -1.0,
            presence_penalty: -1.0,
            frequency_penalty: -1.0,
            seed: 0,
            max_tokens: 0,
        }
    }
}

// =============================================================================
// Opaque Handles
// =============================================================================

/// Opaque handle for Responses/Conversation.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ResponsesHandle {
    _private: [u8; 0],
}

/// Opaque handle for string list.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct StringList {
    _private: [u8; 0],
}

/// Opaque handle for cached model list.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CachedModelList {
    _private: [u8; 0],
}

// =============================================================================
// Callback Types
// =============================================================================

pub type RouterTokenCallback =
    Option<unsafe extern "C" fn(*const c_char, u32, *mut c_void) -> bool>;

/// Unified progress callback - receives structured progress updates from core.
/// This is the new callback type used by all long-running operations.
pub type CProgressCallback = Option<unsafe extern "C" fn(*const ProgressUpdate, *mut c_void)>;

/// Legacy progress callback (deprecated - use CProgressCallback).
pub type ProgressCallback = Option<unsafe extern "C" fn(u64, u64, *mut c_void)>;

/// Legacy file start callback (deprecated - use CProgressCallback).
pub type FileStartCallback = Option<unsafe extern "C" fn(*const c_char, *mut c_void)>;

// =============================================================================
// Type Aliases (Backwards Compatibility)
// =============================================================================
//
// These aliases allow wrapper code to use cleaner names without the C prefix.
// New code should prefer the C-prefixed names to match the Zig C API.
pub type PoolingStrategy = CPoolingStrategy;

/// Alias for CContentPart (legacy name used in some wrapper code)
pub type CResponsesContentPart = CContentPart;
/// Progress action discriminator.
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ProgressAction {
    Add = 0,
    Update = 1,
    Complete = 2,
}

impl Default for ProgressAction {
    fn default() -> Self {
        Self::Update
    }
}

impl From<u8> for ProgressAction {
    fn from(value: u8) -> Self {
        match value {
            0 => ProgressAction::Add,
            1 => ProgressAction::Update,
            2 => ProgressAction::Complete,
            _ => ProgressAction::Update,
        }
    }
}
/// Structured progress update payload.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ProgressUpdate {
    pub line_id: u8,
    pub action: ProgressAction,
    pub current: u64,
    pub total: u64,
    pub label: *const c_char,
    pub message: *const c_char,
    pub unit: *const c_char,
}

impl Default for ProgressUpdate {
    fn default() -> Self {
        Self {
            line_id: 0,
            action: ProgressAction::Update,
            current: 0,
            total: 0,
            label: std::ptr::null(),
            message: std::ptr::null(),
            unit: std::ptr::null(),
        }
    }
}
/// Message role discriminator.
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum MessageRole {
    System = 0,
    User = 1,
    Assistant = 2,
    Developer = 3,
    Unknown = 255,
}

impl From<u8> for MessageRole {
    fn from(value: u8) -> Self {
        match value {
            0 => MessageRole::System,
            1 => MessageRole::User,
            2 => MessageRole::Assistant,
            3 => MessageRole::Developer,
            _ => MessageRole::Unknown,
        }
    }
}
/// Item type discriminator.
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ItemType {
    Message = 0,
    FunctionCall = 1,
    FunctionCallOutput = 2,
    Reasoning = 3,
    ItemReference = 4,
    Unknown = 255,
}

impl From<u8> for ItemType {
    fn from(value: u8) -> Self {
        match value {
            0 => ItemType::Message,
            1 => ItemType::FunctionCall,
            2 => ItemType::FunctionCallOutput,
            3 => ItemType::Reasoning,
            4 => ItemType::ItemReference,
            _ => ItemType::Unknown,
        }
    }
}
// =============================================================================
// Semantic Enums (Not in Zig C API, but documented in field comments)
// =============================================================================
//
// These enums represent values stored in u8 fields with documented meanings.
// They are manually defined here for type safety in Rust wrapper code.

/// Content type discriminator.
/// Matches values documented in CContentPart.content_type.
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ContentType {
    InputText = 0,
    InputImage = 1,
    InputAudio = 2,
    InputFile = 3,
    InputVideo = 4,
    OutputText = 5,
    Refusal = 6,
    Text = 7,
    ReasoningText = 8,
    SummaryText = 9,
    Unknown = 255,
}

impl From<u8> for ContentType {
    fn from(value: u8) -> Self {
        match value {
            0 => ContentType::InputText,
            1 => ContentType::InputImage,
            2 => ContentType::InputAudio,
            3 => ContentType::InputFile,
            4 => ContentType::InputVideo,
            5 => ContentType::OutputText,
            6 => ContentType::Refusal,
            7 => ContentType::Text,
            8 => ContentType::ReasoningText,
            9 => ContentType::SummaryText,
            _ => ContentType::Unknown,
        }
    }
}

/// Image detail level.
/// Matches values documented in CContentPart.image_detail.
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Default)]
pub enum ImageDetail {
    #[default]
    Auto = 0,
    Low = 1,
    High = 2,
}

impl From<u8> for ImageDetail {
    fn from(value: u8) -> Self {
        match value {
            0 => ImageDetail::Auto,
            1 => ImageDetail::Low,
            2 => ImageDetail::High,
            _ => ImageDetail::Auto,
        }
    }
}

/// Item status.
/// Matches values documented in CItem.status and CStorageRecord.status.
#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Default)]
pub enum ItemStatus {
    #[default]
    InProgress = 0,
    Waiting = 1,
    Completed = 2,
    Incomplete = 3,
    Failed = 4,
}

impl From<u8> for ItemStatus {
    fn from(value: u8) -> Self {
        match value {
            0 => ItemStatus::InProgress,
            1 => ItemStatus::Waiting,
            2 => ItemStatus::Completed,
            3 => ItemStatus::Incomplete,
            4 => ItemStatus::Failed,
            _ => ItemStatus::InProgress,
        }
    }
}

// =============================================================================
// C API Functions
// =============================================================================

extern "C" {
    // core/src/capi/memory.zig
    pub fn talu_alloc_string(len: usize) -> *mut u8;
    // core/src/capi/session.zig
    pub fn talu_apply_chat_template(
        model_path: *const c_char,
        messages_json: *const c_char,
        add_generation_prompt: c_int,
        out_prompt: *mut c_void,
    ) -> c_int;
    // core/src/capi/session.zig
    pub fn talu_apply_chat_template_string(
        template_ptr: *const u8,
        template_len: usize,
        messages_json: *const c_char,
        add_generation_prompt: c_int,
        bos_token: *const c_char,
        eos_token: *const c_char,
        out_prompt: *mut c_void,
    ) -> c_int;
    // core/src/capi/router.zig
    pub fn talu_backend_create_from_canonical(
        canon: *mut c_void,
        options: BackendCreateOptions,
        out_backend: *mut c_void,
    ) -> c_int;
    // core/src/capi/router.zig
    pub fn talu_backend_free(backend: *mut c_void);
    // core/src/capi/router.zig
    pub fn talu_backend_get_capabilities(
        backend_type_raw: c_int,
        backend_config: *const BackendUnion,
        out_caps: *mut TaluCapabilities,
    ) -> c_int;
    // core/src/capi/router.zig
    pub fn talu_backend_model_info(backend: *mut c_void) -> CModelInfo;
    // core/src/capi/router.zig
    pub fn talu_backend_synchronize(backend: *mut c_void) -> c_int;
    // core/src/capi/batch.zig
    pub fn talu_batch_active_count(handle: *mut c_void) -> usize;
    // core/src/capi/batch.zig
    pub fn talu_batch_cancel(handle: *mut c_void, request_id: u64) -> u8;
    // core/src/capi/batch.zig
    pub fn talu_batch_create(backend: *mut c_void, config: *const CBatchConfig) -> *mut c_void;
    // core/src/capi/batch.zig
    pub fn talu_batch_destroy(handle: *mut c_void);
    // core/src/capi/tokenizer.zig
    pub fn talu_batch_encode_result_free(
        ids: *mut u32,
        offsets: *mut usize,
        total_tokens: usize,
        num_sequences: usize,
    );
    // core/src/capi/batch.zig
    pub fn talu_batch_has_active(handle: *mut c_void) -> u8;
    // core/src/capi/dlpack.zig
    pub fn talu_batch_mask_to_dlpack(
        ids: *const u32,
        offsets: *const usize,
        num_sequences: usize,
        max_length: usize,
        padding_side: u8,
    ) -> *mut c_void;
    // core/src/capi/batch.zig
    pub fn talu_batch_result_free(result: *mut CBatchResult);
    // core/src/capi/batch.zig
    pub fn talu_batch_run_loop(
        handle: *mut c_void,
        pending_flag: *mut c_void,
        callback: *mut c_void,
        callback_data: *mut c_void,
    ) -> c_int;
    // core/src/capi/batch.zig
    pub fn talu_batch_run_loop_no_text(
        handle: *mut c_void,
        pending_flag: *mut c_void,
        callback: *mut c_void,
        callback_data: *mut c_void,
    ) -> c_int;
    // core/src/capi/batch.zig
    pub fn talu_batch_step(
        handle: *mut c_void,
        events_out: *mut CBatchEvent,
        max_events: usize,
    ) -> usize;
    // core/src/capi/batch.zig
    pub fn talu_batch_submit(
        handle: *mut c_void,
        chat_handle: *mut c_void,
        config: *const CGenerateConfig,
    ) -> u64;
    // core/src/capi/batch.zig
    pub fn talu_batch_take_result(handle: *mut c_void, request_id: u64) -> *mut CBatchResult;
    // core/src/capi/dlpack.zig
    pub fn talu_batch_to_dlpack(
        ids: *const u32,
        offsets: *const usize,
        num_sequences: usize,
        pad_id: u32,
        max_length: usize,
        padding_side: u8,
    ) -> *mut c_void;
    // core/src/capi/tokenizer.zig
    pub fn talu_batch_to_padded_tensor(
        ids: *const u32,
        offsets: *const usize,
        num_sequences: usize,
        options: *const PaddedTensorOptions,
    ) -> PaddedTensorResult;
    // core/src/capi/buffer.zig
    pub fn talu_buffer_create_from_copy(tokens: *const u32, num_tokens: usize) -> *mut c_void;
    // core/src/capi/buffer.zig
    pub fn talu_buffer_create_from_owned(tokens: *mut u32, num_tokens: usize) -> *mut c_void;
    // core/src/capi/buffer.zig
    pub fn talu_buffer_get_data_ptr(handle: *mut c_void) -> *mut u32;
    // core/src/capi/buffer.zig
    pub fn talu_buffer_release(handle: *mut c_void) -> u8;
    // core/src/capi/dlpack.zig
    pub fn talu_buffer_to_dlpack(
        buffer_handle: *mut c_void,
        offset_elems: usize,
        len: usize,
    ) -> *mut c_void;
    // core/src/capi/responses.zig
    pub fn talu_chat_count_tokens(
        chat_handle: *mut c_void,
        model: *const c_char,
        additional_message: *const u8,
        additional_message_len: usize,
    ) -> i64;
    // core/src/capi/responses.zig
    pub fn talu_chat_create(options: *mut ChatCreateOptions) -> *mut c_void;
    // core/src/capi/responses.zig
    pub fn talu_chat_create_with_session(
        session_id: *const c_char,
        options: *mut ChatCreateOptions,
    ) -> *mut c_void;
    // core/src/capi/responses.zig
    pub fn talu_chat_create_with_system(
        system: *const c_char,
        options: *mut ChatCreateOptions,
    ) -> *mut c_void;
    // core/src/capi/responses.zig
    pub fn talu_chat_create_with_system_and_session(
        system: *const c_char,
        session_id: *const c_char,
        options: *mut ChatCreateOptions,
    ) -> *mut c_void;
    // core/src/capi/responses.zig
    pub fn talu_chat_free(handle: *mut c_void);
    // core/src/capi/responses.zig
    pub fn talu_chat_get_conversation(handle: *mut c_void) -> *mut ResponsesHandle;
    // core/src/capi/responses.zig
    pub fn talu_chat_get_prompt_id(handle: *mut c_void) -> *const c_char;
    // core/src/capi/responses.zig
    pub fn talu_chat_get_system(handle: *mut c_void) -> *const c_char;
    // core/src/capi/responses.zig
    pub fn talu_chat_get_tool_choice(handle: *mut c_void) -> *const c_char;
    // core/src/capi/responses.zig
    pub fn talu_chat_get_tools(handle: *mut c_void) -> *const c_char;
    // core/src/capi/responses.zig
    pub fn talu_chat_load_completions_json(
        handle: *mut c_void,
        json_ptr: *const u8,
        json_len: usize,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_chat_max_context_length(model: *const c_char) -> u64;
    // core/src/capi/responses.zig
    pub fn talu_chat_set_messages(handle: *mut c_void, json: *const c_char) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_chat_set_prompt_id(handle: *mut c_void, prompt_id: *const c_char) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_chat_set_system(handle: *mut c_void, system: *const c_char) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_chat_set_tool_choice(
        handle: *mut c_void,
        json: *const c_char,
        json_len: usize,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_chat_set_tools(handle: *mut c_void, json: *const c_char, json_len: usize) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_chat_set_ttl_ts(handle: *mut c_void, ttl_ts: i64) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_chat_to_json(handle: *mut c_void) -> *const c_char;
    // core/src/capi/error.zig
    pub fn talu_clear_error();
    // core/src/capi/validate.zig
    pub fn talu_clear_response_format(chat_handle: *mut c_void);
    // core/src/capi/router.zig
    pub fn talu_completions_validate_request(
        messages_json_ptr: *const u8,
        messages_json_len: usize,
        has_max_tokens: usize,
        max_tokens: i64,
        has_max_completion_tokens: usize,
        max_completion_tokens: i64,
        temperature: f64,
        top_p: f64,
        presence_penalty: f64,
        frequency_penalty: f64,
        tools_json_ptr: *const u8,
        tools_json_len: usize,
        tool_choice_json_ptr: *const u8,
        tool_choice_json_len: usize,
    ) -> c_int;
    // core/src/capi/router.zig
    pub fn talu_config_canonicalize(in_spec: *mut TaluModelSpec, out_handle: *mut c_void) -> c_int;
    // core/src/capi/router.zig
    pub fn talu_config_free(handle: *mut c_void);
    // core/src/capi/router.zig
    pub fn talu_config_get_view(handle: *mut c_void, out_spec: *mut TaluModelSpec) -> c_int;
    // core/src/capi/converter.zig
    pub fn talu_convert(
        model_path: *const c_char,
        output_dir: *const c_char,
        options: *const ConvertOptions,
    ) -> ConvertResult;
    // core/src/capi/converter.zig
    pub fn talu_convert_free_string(string_ptr: *const c_char);
    // core/src/capi/converter.zig
    pub fn talu_convert_parse_scheme(name: *const c_char) -> c_int;
    // core/src/capi/converter.zig
    pub fn talu_convert_schemes(out_schemes: *mut c_void) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_decode_result_free(text: *mut u8, text_len: usize);
    // core/src/capi/converter.zig
    pub fn talu_describe(model_path: *const c_char) -> ModelInfo;
    // core/src/capi/tokenizer.zig
    pub fn talu_encode_result_free(result: EncodeResult);
    // core/src/capi/error.zig
    pub fn talu_error_buf_size() -> usize;
    // core/src/capi/converter.zig
    pub fn talu_execution_plan(info: *mut ModelInfo) -> ExecutionPlanInfo;
    // core/src/capi/template.zig
    pub fn talu_free_spans(spans: *mut COutputSpan, count: u32);
    // core/src/capi/memory.zig
    pub fn talu_free_string(ptr: *mut u8, len: usize);
    // core/src/capi/template.zig
    pub fn talu_get_chat_template_source(
        model_path: *const c_char,
        out_source: *mut c_void,
    ) -> c_int;
    // core/src/capi/session.zig
    pub fn talu_get_eos_tokens(model_dir: *const c_char) -> EosTokenResult;
    // core/src/capi/session.zig
    pub fn talu_get_generation_config(
        model_dir: *const c_char,
        out_config: *mut GenerationConfigInfo,
    ) -> c_int;
    // core/src/capi/log.zig
    pub fn talu_get_log_format() -> c_int;
    // core/src/capi/log.zig
    pub fn talu_get_log_level() -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_grammar_compile(schema_json: *const c_char) -> *mut c_void;
    // core/src/capi/validate.zig
    pub fn talu_grammar_free(handle: *mut c_void);
    // core/src/capi/error.zig
    pub fn talu_last_error() -> *const c_char;
    // core/src/capi/error.zig
    pub fn talu_last_error_code() -> c_int;
    // core/src/capi/converter.zig
    pub fn talu_model_info_free(info: *mut ModelInfo);
    // core/src/capi/converter.zig
    pub fn talu_model_performance_hints(name: *const c_char, out_json: *mut c_void) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_padded_tensor_result_free(
        input_ids: *mut u32,
        attention_mask: *mut u32,
        num_sequences: usize,
        padded_length: usize,
    );
    // core/src/capi/repository.zig
    pub fn talu_repo_cache_dir_exists(model_id: *const c_char) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_delete(model_id: *const c_char) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_fetch(
        model_id: *const c_char,
        options: *mut DownloadOptions,
        out: *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_fetch_file(
        model_id: *const c_char,
        filename: *const c_char,
        options: *mut DownloadOptions,
        out: *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_get_cached_path(
        model_id: *const c_char,
        require_weights: bool,
        out: *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_get_hf_home(out: *mut c_void) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_get_talu_home(out: *mut c_void) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_is_cached(model_id: *const c_char) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_is_model_id(path: *const c_char) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_list(
        model_path: *const c_char,
        token: *const c_char,
        out: *mut *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_list_count(list: *mut CachedModelList) -> usize;
    // core/src/capi/repository.zig
    pub fn talu_repo_list_free(list: *mut CachedModelList);
    // core/src/capi/repository.zig
    pub fn talu_repo_list_get_id(list: *mut CachedModelList, idx: usize, out: *mut c_void)
        -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_list_get_path(
        list: *mut CachedModelList,
        idx: usize,
        out: *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_list_get_source(list: *mut CachedModelList, idx: usize) -> u8;
    // core/src/capi/repository.zig
    pub fn talu_repo_list_models(require_weights: bool, out: *mut *mut c_void) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_mtime(model_id: *const c_char) -> i64;
    // core/src/capi/repository.zig
    pub fn talu_repo_resolve_path(
        uri: *const c_char,
        offline: bool,
        token: *const c_char,
        endpoint_url: *const c_char,
        require_weights: bool,
        out_path: *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_search(
        query: *const c_char,
        limit: usize,
        token: *const c_char,
        endpoint_url: *const c_char,
        out: *mut *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_count(list: *mut c_void) -> usize;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_free(list: *mut c_void);
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_get_downloads(list: *mut c_void, idx: usize) -> i64;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_get_id(list: *mut c_void, idx: usize, out: *mut c_void)
        -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_get_last_modified(
        list: *mut c_void,
        idx: usize,
        out: *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_get_likes(list: *mut c_void, idx: usize) -> i64;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_get_params(list: *mut c_void, idx: usize) -> i64;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_result_get_pipeline_tag(
        list: *mut c_void,
        idx: usize,
        out: *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_search_rich(
        query: *const c_char,
        limit: usize,
        token: *const c_char,
        endpoint_url: *const c_char,
        filter: *const c_char,
        sort: u8,
        direction: u8,
        library: *const c_char,
        out: *mut *mut c_void,
    ) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_size(model_id: *const c_char) -> u64;
    // core/src/capi/repository.zig
    pub fn talu_repo_string_list_count(list: *mut StringList) -> usize;
    // core/src/capi/repository.zig
    pub fn talu_repo_string_list_free(list: *mut StringList);
    // core/src/capi/repository.zig
    pub fn talu_repo_string_list_get(list: *mut StringList, idx: usize, out: *mut c_void) -> c_int;
    // core/src/capi/repository.zig
    pub fn talu_repo_total_size() -> u64;
    // core/src/capi/session.zig
    pub fn talu_resolve_effective_generation_config(
        model_dir: *const c_char,
        request: *const EffectiveGenConfigRequest,
        out_config: *mut EffectiveGenConfig,
    ) -> c_int;
    // core/src/capi/session.zig
    pub fn talu_resolve_model_path(model_path: *const c_char, out_path: *mut c_void) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_append_function_call(
        handle: *mut ResponsesHandle,
        call_id: *const c_char,
        name: *const c_char,
        arguments_ptr: *const u8,
        arguments_len: usize,
    ) -> i64;
    // core/src/capi/responses.zig
    pub fn talu_responses_append_function_call_output(
        handle: *mut ResponsesHandle,
        call_id: *const c_char,
        output_ptr: *const u8,
        output_len: usize,
    ) -> i64;
    // core/src/capi/responses.zig
    pub fn talu_responses_append_message(
        handle: *mut ResponsesHandle,
        role: u8,
        content_ptr: *const u8,
        content_len: usize,
    ) -> i64;
    // core/src/capi/responses.zig
    pub fn talu_responses_append_message_hidden(
        handle: *mut ResponsesHandle,
        role: u8,
        content_ptr: *const u8,
        content_len: usize,
        hidden: bool,
    ) -> i64;
    // core/src/capi/responses.zig
    pub fn talu_responses_append_text_content(
        handle: *mut ResponsesHandle,
        item_index: usize,
        content_ptr: *const u8,
        content_len: usize,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_clear(handle: *mut ResponsesHandle);
    // core/src/capi/responses.zig
    pub fn talu_responses_clear_keeping_system(handle: *mut ResponsesHandle);
    // core/src/capi/responses.zig
    pub fn talu_responses_clone(
        dest_handle: *mut ResponsesHandle,
        source_handle: *mut ResponsesHandle,
        batch_size: usize,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_clone_prefix(
        dest_handle: *mut ResponsesHandle,
        source_handle: *mut ResponsesHandle,
        last_index: usize,
        batch_size: usize,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_create() -> *mut ResponsesHandle;
    // core/src/capi/responses.zig
    pub fn talu_responses_create_with_session(session_id: *const c_char) -> *mut ResponsesHandle;
    // core/src/capi/responses.zig
    pub fn talu_responses_free(handle: *mut ResponsesHandle);
    // core/src/capi/responses.zig
    pub fn talu_responses_get_item(
        handle: *mut ResponsesHandle,
        index: usize,
        out: *mut CItem,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_insert_message(
        handle: *mut ResponsesHandle,
        index: usize,
        role: u8,
        content_ptr: *const u8,
        content_len: usize,
    ) -> i64;
    // core/src/capi/responses.zig
    pub fn talu_responses_insert_message_hidden(
        handle: *mut ResponsesHandle,
        index: usize,
        role: u8,
        content_ptr: *const u8,
        content_len: usize,
        hidden: bool,
    ) -> i64;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_as_function_call(
        handle: *mut ResponsesHandle,
        index: usize,
        out: *mut CFunctionCallItem,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_as_function_call_output(
        handle: *mut ResponsesHandle,
        index: usize,
        out: *mut CFunctionCallOutputItem,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_as_item_reference(
        handle: *mut ResponsesHandle,
        index: usize,
        out: *mut CItemReferenceItem,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_as_message(
        handle: *mut ResponsesHandle,
        index: usize,
        out: *mut CMessageItem,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_as_reasoning(
        handle: *mut ResponsesHandle,
        index: usize,
        out: *mut CReasoningItem,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_count(handle: *mut ResponsesHandle) -> usize;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_fco_get_part(
        handle: *mut ResponsesHandle,
        item_index: usize,
        part_index: usize,
        out: *mut CContentPart,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_get_generation_json(
        handle: *mut ResponsesHandle,
        index: usize,
        out_ptr: *mut c_void,
        out_len: *mut c_void,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_message_content_count(
        handle: *mut ResponsesHandle,
        index: usize,
    ) -> usize;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_message_get_content(
        handle: *mut ResponsesHandle,
        item_index: usize,
        part_index: usize,
        out: *mut CContentPart,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_reasoning_content_count(
        handle: *mut ResponsesHandle,
        index: usize,
    ) -> usize;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_reasoning_get_content(
        handle: *mut ResponsesHandle,
        item_index: usize,
        part_index: usize,
        out: *mut CContentPart,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_reasoning_get_summary(
        handle: *mut ResponsesHandle,
        item_index: usize,
        part_index: usize,
        out: *mut CContentPart,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_reasoning_summary_count(
        handle: *mut ResponsesHandle,
        index: usize,
    ) -> usize;
    // core/src/capi/responses.zig
    pub fn talu_responses_item_type(handle: *mut ResponsesHandle, index: usize) -> u8;
    // core/src/capi/responses.zig
    pub fn talu_responses_load_completions_json(
        handle: *mut ResponsesHandle,
        json: *const c_char,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_load_responses_json(
        handle: *mut ResponsesHandle,
        json: *const c_char,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_pop(handle: *mut ResponsesHandle) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_remove(handle: *mut ResponsesHandle, index: usize) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_set_item_status(
        handle: *mut ResponsesHandle,
        item_index: usize,
        status: u8,
    ) -> c_int;
    // core/src/capi/responses.zig
    pub fn talu_responses_to_completions_json(handle: *mut ResponsesHandle) -> *const c_char;
    // core/src/capi/responses.zig
    pub fn talu_responses_to_responses_json(
        handle: *mut ResponsesHandle,
        direction: u8,
    ) -> *const c_char;
    // core/src/capi/responses.zig
    pub fn talu_responses_truncate_after(handle: *mut ResponsesHandle, last_index: usize) -> c_int;
    // core/src/capi/router.zig
    pub fn talu_router_close_all();
    // core/src/capi/router.zig
    pub fn talu_router_embed(
        model: *const c_char,
        text: *const c_char,
        pooling: CPoolingStrategy,
        normalize: bool,
        out_embedding: *mut c_void,
        out_dim: *mut c_void,
    ) -> c_int;
    // core/src/capi/router.zig
    pub fn talu_router_embedding_dim(model: *const c_char) -> usize;
    // core/src/capi/router.zig
    pub fn talu_router_embedding_free(embedding: *const f32, dim: usize);
    // core/src/capi/router.zig
    pub fn talu_router_generate_streaming(
        chat_handle: *mut c_void,
        parts: *const GenerateContentPart,
        num_parts: usize,
        backend: *mut c_void,
        config: *const CGenerateConfig,
        stream_cb: *mut c_void,
        stream_cb_data: *mut c_void,
    ) -> CGenerateResult;
    // core/src/capi/router.zig
    pub fn talu_router_generate_with_backend(
        chat_handle: *mut c_void,
        parts: *const GenerateContentPart,
        num_parts: usize,
        backend: *mut c_void,
        config: *const CGenerateConfig,
    ) -> CGenerateResult;
    // core/src/capi/router.zig
    pub fn talu_router_result_free(result: *mut CGenerateResult);
    // core/src/capi/scheduler.zig
    pub fn talu_scheduler_score_tokens_joint(
        reference_backend: *mut c_void,
        model_backend: *mut c_void,
        context_tokens: *const u32,
        context_len: usize,
        target_tokens: *const u32,
        target_len: usize,
        max_context: usize,
        out_reference_nll: *mut c_void,
        out_model_nll: *mut c_void,
        out_kld: *mut c_void,
        out_scored_tokens: *mut c_void,
    ) -> c_int;
    // core/src/capi/scheduler.zig
    pub fn talu_scheduler_score_tokens_nll(
        backend: *mut c_void,
        context_tokens: *const u32,
        context_len: usize,
        target_tokens: *const u32,
        target_len: usize,
        max_context: usize,
        out_nll: *mut c_void,
        out_scored_tokens: *mut c_void,
    ) -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_semantic_validator_check(
        handle: *mut c_void,
        json_str: *const u8,
        json_len: usize,
        out_violation: *mut SemanticViolationC,
    ) -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_semantic_validator_create(schema_json: *const c_char) -> *mut c_void;
    // core/src/capi/validate.zig
    pub fn talu_semantic_validator_destroy(handle: *mut c_void);
    // core/src/capi/responses.zig
    pub fn talu_session_id_new(out_session_id: *mut c_void) -> c_int;
    // core/src/capi/log.zig
    pub fn talu_set_log_callback(callback: *mut c_void, user_data: *mut c_void);
    // core/src/capi/log.zig
    pub fn talu_set_log_filter(ptr: *const u8, len: usize);
    // core/src/capi/log.zig
    pub fn talu_set_log_format(format: c_int);
    // core/src/capi/log.zig
    pub fn talu_set_log_level(level: c_int);
    // core/src/capi/validate.zig
    pub fn talu_set_response_format(
        chat_handle: *mut c_void,
        schema_json: *const c_char,
        config: *const ValidateConfigC,
        stop_tokens: *const u32,
        stop_tokens_len: usize,
        prefix_token_ids: *const u32,
        prefix_token_ids_len: usize,
    ) -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_set_response_format_handle(
        chat_handle: *mut c_void,
        grammar_handle: *mut c_void,
        config: *const ValidateConfigC,
        stop_tokens: *const u32,
        stop_tokens_len: usize,
        prefix_token_ids: *const u32,
        prefix_token_ids_len: usize,
    ) -> c_int;
    // core/src/capi/error.zig
    pub fn talu_take_last_error(
        out_buf: *mut u8,
        out_buf_size: usize,
        out_code: *mut c_void,
    ) -> usize;
    // core/src/capi/template.zig
    pub fn talu_template_render(
        template_str: *const c_char,
        json_vars: *const c_char,
        strict: bool,
        out_rendered: *mut c_void,
    ) -> c_int;
    // core/src/capi/template.zig
    pub fn talu_template_render_debug(
        template_str: *const c_char,
        json_vars: *const c_char,
        strict: bool,
        out_rendered: *mut c_void,
        out_spans: *mut c_void,
        out_span_count: *mut c_void,
    ) -> c_int;
    // core/src/capi/template.zig
    pub fn talu_template_render_with_filters(
        template_str: *const c_char,
        json_vars: *const c_char,
        strict: bool,
        filter_names: *const *const c_char,
        filter_callbacks: *mut c_void,
        filter_user_data: *mut c_void,
        num_filters: usize,
        out_rendered: *mut c_void,
    ) -> c_int;
    // core/src/capi/template.zig
    pub fn talu_template_validate(
        template_str: *const c_char,
        json_vars: *const c_char,
        out_result_json: *mut c_void,
    ) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_text_free(text: *const c_char);
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenize_bytes_result_free(
        data: *mut u8,
        data_len: usize,
        offsets: *mut usize,
        num_tokens: usize,
    );
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenize_result_free(tokens: *const *const c_char, num_tokens: usize);
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_create(model_path: *const c_char, out_tokenizer: *mut c_void) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_create_from_json(
        json_ptr: *const u8,
        json_len: usize,
        out_tokenizer: *mut c_void,
    ) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_decode(
        handle: *mut c_void,
        tokens: *const u32,
        num_tokens: usize,
        options: *const DecodeOptionsC,
    ) -> DecodeResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_encode(
        handle: *mut c_void,
        text: *const u8,
        text_len: usize,
        options: *const EncodeOptions,
    ) -> EncodeResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_encode_batch(
        handle: *mut c_void,
        texts: *const *const u8,
        lengths: *const usize,
        num_texts: usize,
        options: *const EncodeOptions,
    ) -> BatchEncodeResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_free(handle: *mut c_void);
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_get_eos_tokens(handle: *mut c_void) -> EosTokenResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_get_model_dir(handle: *mut c_void, out_path: *mut c_void) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_get_model_max_length(handle: *mut c_void) -> u64;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_get_special_tokens(handle: *mut c_void) -> SpecialTokensResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_get_vocab(handle: *mut c_void) -> VocabResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_get_vocab_size(handle: *mut c_void) -> usize;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_id_to_token(
        handle: *mut c_void,
        token_id: c_int,
        out_token: *mut c_void,
    ) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_token_to_id(
        handle: *mut c_void,
        token: *const u8,
        token_len: usize,
    ) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_tokenize(
        handle: *mut c_void,
        text: *const u8,
        text_len: usize,
    ) -> TokenizeResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokenizer_tokenize_bytes(
        handle: *mut c_void,
        text: *const u8,
        text_len: usize,
    ) -> TokenizeBytesResult;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokens_concat(
        tokens_a: *const u32,
        num_a: usize,
        tokens_b: *const u32,
        num_b: usize,
    ) -> *mut u32;
    // core/src/capi/tokenizer.zig
    pub fn talu_tokens_free(tokens: *mut u32, num_tokens: usize);
    // core/src/capi/train.zig
    pub fn talu_train_configure(handle: *mut c_void, config: *mut c_void) -> c_int;
    // core/src/capi/train.zig
    pub fn talu_train_create(out: *mut c_void) -> c_int;
    // core/src/capi/train.zig
    pub fn talu_train_destroy(handle: *mut c_void);
    // core/src/capi/train_full.zig
    pub fn talu_train_full_configure(
        handle: *mut c_void,
        config: *const CFullSessionConfig,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_copy_optimizer_state_f32(
        handle: *mut c_void,
        out_state: *const f32,
        out_len: usize,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_copy_weights_f32(
        handle: *mut c_void,
        out_weights: *const f32,
        out_len: usize,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_create(out: *mut c_void) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_destroy(handle: *mut c_void);
    // core/src/capi/train_full.zig
    pub fn talu_train_full_get_info(handle: *mut c_void, out_info: *mut CFullSessionInfo) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_init_model(
        handle: *mut c_void,
        config: *const CTransformerConfig,
        seed: u64,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_load_data(handle: *mut c_void, data_path: *const c_char) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_load_optimizer_state_f32(
        handle: *mut c_void,
        in_state: *const f32,
        in_len: usize,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_load_weights_f32(
        handle: *mut c_void,
        in_weights: *const f32,
        in_len: usize,
        step: u64,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_run(
        handle: *mut c_void,
        callback: *mut c_void,
        user_data: *mut c_void,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_set_data(
        handle: *mut c_void,
        tokens_ptr: *const u32,
        tokens_len: usize,
    ) -> c_int;
    // core/src/capi/train_full.zig
    pub fn talu_train_full_step(handle: *mut c_void, out_metrics: *mut c_void) -> c_int;
    // core/src/capi/train.zig
    pub fn talu_train_get_info(handle: *mut c_void, out_info: *mut c_void) -> c_int;
    // core/src/capi/train.zig
    pub fn talu_train_load_data(handle: *mut c_void, data_path: *const c_char) -> c_int;
    // core/src/capi/train.zig
    pub fn talu_train_load_model(
        handle: *mut c_void,
        model_path: *const c_char,
        lora_config: *mut c_void,
        target_modules: *const *const c_char,
        num_targets: usize,
    ) -> c_int;
    // core/src/capi/train.zig
    pub fn talu_train_run(
        handle: *mut c_void,
        callback: *mut c_void,
        user_data: *mut c_void,
    ) -> c_int;
    // core/src/capi/train.zig
    pub fn talu_train_save_checkpoint(handle: *mut c_void, output_path: *const c_char) -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_advance(handle: *mut c_void, bytes: *const u8, len: usize)
        -> usize;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_can_accept(
        handle: *mut c_void,
        bytes: *const u8,
        len: usize,
    ) -> bool;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_create(schema_json: *const c_char) -> *mut c_void;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_destroy(handle: *mut c_void);
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_get_position(handle: *mut c_void) -> usize;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_get_valid_bytes(
        handle: *mut c_void,
        out_valid: *mut c_void,
    ) -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_is_complete(handle: *mut c_void) -> bool;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_reset(handle: *mut c_void) -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_validate_engine_validate(
        handle: *mut c_void,
        bytes: *const u8,
        len: usize,
    ) -> c_int;
    // core/src/capi/validate.zig
    pub fn talu_validate_response_format(
        chat_handle: *mut c_void,
        out_result: *mut SemanticValidationResultC,
    ) -> c_int;
    // core/src/capi/tokenizer.zig
    pub fn talu_vocab_result_free(
        tokens: *const *const c_char,
        lengths: *mut u32,
        ids: *mut u32,
        num_entries: usize,
    );
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_clear(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_count(handle: *mut c_void) -> usize;
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_create(points_mask: u32, mode: u8, sample_count: u32) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_create_all(mode: u8, sample_count: u32) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_destroy(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_disable();
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_enable(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_is_enabled() -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_capture_overflow(handle: *mut c_void) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_count_matching(
        handle: *mut c_void,
        point: u8,
        layer: u16,
        token: u32,
    ) -> usize;
    // core/src/capi/xray.zig
    pub fn talu_xray_find_anomaly(
        handle: *mut c_void,
        out_point: *mut c_void,
        out_layer: *mut c_void,
        out_token: *mut c_void,
    ) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_get(handle: *mut c_void, index: usize, out: *mut CapturedTensorInfo) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_get_data(
        handle: *mut c_void,
        index: usize,
        out_data: *mut u8,
        max_len: usize,
    ) -> usize;
    // core/src/capi/xray.zig
    pub fn talu_xray_get_data_size(handle: *mut c_void, index: usize) -> usize;
    // core/src/capi/xray.zig
    pub fn talu_xray_get_samples(
        handle: *mut c_void,
        index: usize,
        out_samples: *const f32,
        max_samples: usize,
    ) -> usize;
    // core/src/capi/xray.zig
    pub fn talu_xray_point_name(point: u8) -> *const c_char;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_data_destroy(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_data_load_json(file_path: *const c_char) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_data_save_json(
        handle: *mut c_void,
        file_path: *const c_char,
    ) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_recorder_create(
        model_name: *const c_char,
        seed: u64,
        temperature: f32,
        max_tokens: u32,
    ) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_recorder_destroy(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_recorder_finalize(handle: *mut c_void) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_recorder_next_token(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_recorder_record_token(handle: *mut c_void, token_id: u32) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_verifier_create(
        ref_data_handle: *mut c_void,
        rel_tolerance: f32,
        abs_tolerance: f32,
    ) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_verifier_destroy(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_verifier_finish(handle: *mut c_void) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_verifier_get_next_token(handle: *mut c_void) -> u32;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_verifier_has_diverged(handle: *mut c_void) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_reference_verifier_next_token(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_teacher_forcing_disable();
    // core/src/capi/xray.zig
    pub fn talu_xray_teacher_forcing_enable_with_verifier(verifier_handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_teacher_forcing_get_next_token() -> u32;
    // core/src/capi/xray.zig
    pub fn talu_xray_teacher_forcing_is_enabled() -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_capture_create_recording(recorder_handle: *mut c_void) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_capture_create_verification(
        verifier_handle: *mut c_void,
        panic_dump_dir: *const c_char,
    ) -> *mut c_void;
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_capture_destroy(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_capture_disable();
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_capture_enable(handle: *mut c_void);
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_capture_save_recording_full_npz(
        handle: *mut c_void,
        file_path: *const c_char,
    ) -> bool;
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_clear_exact_emission_filter();
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_clear_full_capture_override();
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_clear_ignore_token_parity_override();
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_clear_point_mask_override();
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_clear_token_only_override();
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_set_exact_emission_filter(point: u8, layer: u16, position: u32);
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_set_full_capture(enabled: bool);
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_set_ignore_token_parity(enabled: bool);
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_set_point_mask(mask: u64);
    // core/src/capi/xray.zig
    pub fn talu_xray_verify_set_token_only(enabled: bool);
}

// =============================================================================
// Safe Helpers
// =============================================================================

/// Safe wrapper for xray capture creation.
pub fn xray_capture_create(points_mask: u32, mode: u8, sample_count: u32) -> *mut c_void {
    unsafe { talu_xray_capture_create(points_mask, mode, sample_count) }
}

/// Safe wrapper for xray capture creation (all points).
pub fn xray_capture_create_all(mode: u8, sample_count: u32) -> *mut c_void {
    unsafe { talu_xray_capture_create_all(mode, sample_count) }
}

/// Safe wrapper to enable xray capture.
pub fn xray_capture_enable(handle: *mut c_void) {
    unsafe { talu_xray_capture_enable(handle) }
}

/// Safe wrapper to disable xray capture.
pub fn xray_capture_disable() {
    unsafe { talu_xray_capture_disable() }
}

/// Safe wrapper to destroy xray capture.
pub fn xray_capture_destroy(handle: *mut c_void) {
    unsafe { talu_xray_capture_destroy(handle) }
}

/// Safe wrapper to get xray capture count.
pub fn xray_capture_count(handle: *mut c_void) -> usize {
    unsafe { talu_xray_capture_count(handle) }
}

/// Safe wrapper to get a captured tensor info entry.
pub fn xray_get(handle: *mut c_void, index: usize, info: &mut CapturedTensorInfo) -> bool {
    unsafe { talu_xray_get(handle, index, info as *mut CapturedTensorInfo) }
}

/// Safe wrapper to get xray point name.
pub fn xray_point_name(point: u8) -> &'static str {
    let ptr = unsafe { talu_xray_point_name(point) };
    if ptr.is_null() {
        "unknown"
    } else {
        unsafe { std::ffi::CStr::from_ptr(ptr) }
            .to_str()
            .unwrap_or("unknown")
    }
}
