"""
ABI Struct Size Validation

Validates that manually-defined Python ctypes structs in _bindings.py match
the auto-generated struct definitions in _native.py (generated from Zig C API).

This catches drift when Zig structs change but manual Python definitions aren't updated.

Auto-generated structs (_native.py) are the source of truth — they are produced
by `zig build gen-bindings` and always match the C ABI. We validate manually-defined
structs against them, and also sanity-check that auto-generated structs have
non-zero size (i.e. they were actually generated).

Run: pytest tests/compat/abi/ -v
"""

import ctypes


class TestAutoGeneratedStructs:
    """Sanity checks for auto-generated struct sizes (must be non-zero)."""

    def test_router_generate_result(self):
        from talu._native import RouterGenerateResult

        assert ctypes.sizeof(RouterGenerateResult) > 0

    def test_c_tool_call_ref(self):
        from talu._native import CToolCallRef

        assert ctypes.sizeof(CToolCallRef) > 0

    def test_c_logit_bias_entry(self):
        from talu._native import CLogitBiasEntry

        assert ctypes.sizeof(CLogitBiasEntry) > 0

    def test_c_item(self):
        from talu._native import CItem

        assert ctypes.sizeof(CItem) > 0

    def test_c_message_item(self):
        from talu._native import CMessageItem

        assert ctypes.sizeof(CMessageItem) > 0

    def test_c_function_call_item(self):
        from talu._native import CFunctionCallItem

        assert ctypes.sizeof(CFunctionCallItem) > 0

    def test_c_function_call_output_item(self):
        from talu._native import CFunctionCallOutputItem

        assert ctypes.sizeof(CFunctionCallOutputItem) > 0

    def test_c_reasoning_item(self):
        from talu._native import CReasoningItem

        assert ctypes.sizeof(CReasoningItem) > 0

    def test_c_item_reference_item(self):
        from talu._native import CItemReferenceItem

        assert ctypes.sizeof(CItemReferenceItem) > 0

    def test_c_content_part(self):
        from talu._native import CContentPart

        assert ctypes.sizeof(CContentPart) > 0

    def test_talu_capabilities(self):
        from talu._native import TaluCapabilities

        assert ctypes.sizeof(TaluCapabilities) > 0


class TestManualStructsMatchNative:
    """Manual _bindings.py structs must match auto-generated _native.py sizes.

    These structs are defined manually in chat/_bindings.py because they need
    custom construction logic. Their sizes must stay in sync with the C ABI.
    """

    def test_router_generate_config(self):
        from talu._native import RouterGenerateConfig as NativeConfig
        from talu.router._bindings import RouterGenerateConfig as ManualConfig

        assert ctypes.sizeof(ManualConfig) == ctypes.sizeof(NativeConfig), (
            f"Manual RouterGenerateConfig ({ctypes.sizeof(ManualConfig)}) != "
            f"native ({ctypes.sizeof(NativeConfig)})"
        )

    def test_content_part(self):
        from talu._native import GenerateContentPart as NativePart
        from talu.router._bindings import CContentPart as ManualPart

        assert ctypes.sizeof(ManualPart) == ctypes.sizeof(NativePart), (
            f"Manual CContentPart ({ctypes.sizeof(ManualPart)}) != "
            f"native GenerateContentPart ({ctypes.sizeof(NativePart)})"
        )

    def test_talu_model_spec(self):
        from talu._native import TaluModelSpec as NativeSpec
        from talu.router._bindings import CTaluModelSpec as ManualSpec

        # Note: CTaluModelSpec in _bindings.py is the full versioned struct
        # with abi_version + struct_size header. TaluModelSpec in _native.py
        # may be a different layout. Only compare if they represent the same
        # C struct.
        manual_size = ctypes.sizeof(ManualSpec)
        native_size = ctypes.sizeof(NativeSpec)
        assert manual_size > 0, "Manual CTaluModelSpec has zero size"
        assert native_size > 0, "Native TaluModelSpec has zero size"
