"""
Template Composition - Use {% include %} for modular, reusable templates.

Primary API: talu.PromptTemplate, talu.template.PromptTemplate
Scope: Single

Use {% include %} to compose templates from smaller parts. This enables:
- Reusable template snippets (headers, footers, formatters)
- Dynamic template selection at runtime
- Shared macros across templates

Related:
- examples/developers/template/environment.py
"""

import talu

# =============================================================================
# Basic Include - Inline Template Strings
# =============================================================================

# Include a template variable that contains another template
template = talu.PromptTemplate("""
{% include header %}

{{ content }}

{% include footer %}
""")

print("Basic include:")
print(
    template(
        header="=== {{ title }} ===",
        footer="---\nGenerated by {{ author }}",
        title="My Document",
        content="This is the main content.",
        author="Talu",
    )
)
print()

# =============================================================================
# Conditional Includes
# =============================================================================

# Include different templates based on conditions
adaptive_template = talu.PromptTemplate("""
{% if format == 'markdown' %}
{% include md_format %}
{% elif format == 'json' %}
{% include json_format %}
{% else %}
{% include plain_format %}
{% endif %}
""")

md_format = "# {{ title }}\n\n{{ content }}"
json_format = '{"title": "{{ title }}", "content": "{{ content }}"}'
plain_format = "{{ title }}: {{ content }}"

print("Conditional includes:")
print("Markdown:", adaptive_template(
    format="markdown",
    md_format=md_format,
    json_format=json_format,
    plain_format=plain_format,
    title="Hello",
    content="World",
).strip())

print("JSON:", adaptive_template(
    format="json",
    md_format=md_format,
    json_format=json_format,
    plain_format=plain_format,
    title="Hello",
    content="World",
).strip())
print()

# =============================================================================
# Shared Macros
# =============================================================================

# Define reusable macros in an included template
main_template = talu.PromptTemplate("""
{% include utils %}

User Info:
{{ format_user(user) }}

Order Summary:
{% for order in orders %}
{{ format_order(order) }}
{% endfor %}
""")

# Macro definitions in a separate "utils" template
utils_macros = """
{% macro format_user(u) %}
Name: {{ u.name }} | Email: {{ u.email }}
{% endmacro %}

{% macro format_order(o) %}
  - Order #{{ o.id }}: ${{ o.total | round(2) }} ({{ o.items | length }} items)
{% endmacro %}
"""

print("Shared macros:")
print(
    main_template(
        utils=utils_macros,
        user={"name": "Alice", "email": "alice@example.com"},
        orders=[
            {"id": "001", "total": 99.99, "items": ["a", "b"]},
            {"id": "002", "total": 149.50, "items": ["c"]},
        ],
    )
)
print()

# =============================================================================
# Nested Includes
# =============================================================================

# Templates can include other templates that include more templates
outer = talu.PromptTemplate("[ {% include middle %} ]")

print("Nested includes:")
print(
    outer(
        middle="( {% include inner %} )",
        inner="{{ value }}",
        value="DEEP",
    )
)
print()

# =============================================================================
# RAG with Pluggable Document Formatters
# =============================================================================

rag_template = talu.PromptTemplate("""
Context:
{% include doc_formatter %}

Question: {{ question }}

Instructions: {{ instructions | default('Answer based on the context above.') }}
""")

# Different document formatting strategies
bullet_formatter = """
{% for doc in documents %}
- {{ doc.content }}
{% endfor %}
"""

numbered_formatter = """
{% for doc in documents %}
[{{ loop.index }}] {{ doc.content }}
{% endfor %}
"""

xml_formatter = """
{% for doc in documents %}
<document id="{{ loop.index }}">
{{ doc.content }}
</document>
{% endfor %}
"""

documents = [
    {"content": "Paris is the capital of France."},
    {"content": "The Eiffel Tower is in Paris."},
]
question = "What is the capital of France?"

print("RAG with bullet formatter:")
print(rag_template(doc_formatter=bullet_formatter, documents=documents, question=question))

print("RAG with numbered formatter:")
print(rag_template(doc_formatter=numbered_formatter, documents=documents, question=question))

print("RAG with XML formatter:")
print(rag_template(doc_formatter=xml_formatter, documents=documents, question=question))

# =============================================================================
# Chat Template with Tool Schema Injection
# =============================================================================

chat_template = talu.PromptTemplate("""
{% for message in messages %}
<|im_start|>{{ message.role }}
{{ message.content }}<|im_end|>
{% endfor %}
{% if tools %}
{% include tool_schema %}
{% endif %}
<|im_start|>assistant
""")

tool_schema = """
<|im_start|>system
You have access to these tools:
{% for tool in tools %}
- {{ tool.name }}: {{ tool.description }}
{% endfor %}
<|im_end|>
"""

print("Chat with tool schema:")
print(
    chat_template(
        messages=[{"role": "user", "content": "What's the weather in Paris?"}],
        tools=[
            {"name": "get_weather", "description": "Get current weather for a city"},
            {"name": "search", "description": "Search the web"},
        ],
        tool_schema=tool_schema,
    )
)

"""
Topics covered:
* template.render
* template.control.flow
"""
